[package]
name = "test-gashapon"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "demo"
test = false
doc = false
path = "bin/demo.rs"

[[bin]]
name = "gui"
test = false
doc = false
path = "bin/gui.rs"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced", branch = "master" }
