name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create folder
        shell: bash
        run: mkdir -p dist
      - name: "Dioxus Deploy"
        uses: DioxusLabs/deploy-action@0.1.2
        with:
          rootPath: "./gashapon_ui/"
