name: github pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Install Dioxus-CLI
        shell: bash
        run: cargo install dioxus-cli

      - name: Build Project 🎁
        shell: bash
        run: dx bundle --release --out-dir docs -p gashapon_ui && mv docs/public/* docs && cp ./docs/index.html ./docs/404.html

      - name: Deploy Project 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: ./docs
          clean: false

